# sudo dnf -y install dnf-plugins-core

- name: Install dnf-plugins-core
  yum:
    name: dnf-plugins-core
    state: present
    update_cache: yes

 #sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
 
- name: Add docker repo to yum repos
  shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo 

 #sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
 
- name: Install docker
  yum:
    name: 
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin
    state: present
    update_cache: yes

 #sudo systemctl enable --now docker

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Add usr to docekr group 
  shell: usermod -aG docker coco 
