# [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64

- name: Download binaries
  shell: "[ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.29.0/kind-linux-amd64"

# chmod +x ./kind
- name: make binaries executable
  shell: chmod +x ./kind

# sudo mv ./kind /usr/local/bin/kind
- name: move kind to bin
  shell: mv ./kind /usr/local/bin/kind