name: deploy nodejs application
# on:
#   push:
#     branches:
#     - main
#     paths:
#     - "app/**"

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:

      - name: checkout the repo
        uses: actions/checkout@v4.2.2
    
      - name: get the build number
        id: get_version
        run: |
          version=$(cat current_version.txt)
          next_version=$((version + 1))
          echo "$next_version" > current_version.txt
          echo "image_version=$next_version" >> $GITHUB_OUTPUT  
     
      - name: check the version
        run: echo "the new version is ${{ steps.get_version.outputs.image_version }}" 


      - name: update the version in the deployment file
        run:  sed -i 's/:v[0-9][0-9]*/:v${{ steps.get_version.outputs.image_version }}/g' k8s/nodejs-dep.yaml         

      - name: Commit and push updated version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add current_version.txt k8s/nodejs-dep.yaml 
          git commit -m "CI: update version to ${{ steps.get_version.outputs.image_version }}" || echo "No changes to commit"
          git push

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build the image and push it
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fortstak-task:v${{ steps.get_version.outputs.image_version }}